USE [master]
GO

/****** Object:  Database [ACME]    Script Date: 8/23/2017 4:28:32 PM ******/
CREATE DATABASE [ACME]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ACME', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.JNSQL\MSSQL\DATA\ACME.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ACME_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.JNSQL\MSSQL\DATA\ACME_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ACME] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ACME].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ACME] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ACME] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ACME] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ACME] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ACME] SET ARITHABORT OFF 
GO

ALTER DATABASE [ACME] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ACME] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ACME] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ACME] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ACME] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ACME] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ACME] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ACME] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ACME] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ACME] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ACME] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ACME] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ACME] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ACME] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ACME] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ACME] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ACME] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ACME] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ACME] SET RECOVERY FULL 
GO

ALTER DATABASE [ACME] SET  MULTI_USER 
GO

ALTER DATABASE [ACME] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ACME] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ACME] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ACME] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ACME] SET  READ_WRITE 
GO


